# Generated by Django 4.1.6 on 2023-02-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("address", models.TextField()),
                ("profile_image", models.ImageField(upload_to="farmer_images")),
            ],
        ),
        migrations.CreateModel(
            name="FarmingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_received", models.CharField(max_length=100)),
                ("payment_done", models.BooleanField()),
                ("product_sold", models.CharField(max_length=100)),
                ("product_remaining", models.CharField(max_length=100)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmerdetails.farmer",
                    ),
                ),
            ],
        ),
    ]
