# Generated by Django 4.1.6 on 2023-02-26 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("farmerdetails", "0002_alter_farmingdetails_payment_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmingdetails",
            name="added_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
