# Generated by Django 4.1.6 on 2023-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerdetails", "0003_farmingdetails_added_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmingdetails",
            name="added_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
