# Generated by Django 4.1.6 on 2023-02-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerdetails", "0004_alter_farmingdetails_added_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmingdetails",
            name="payment_done",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmingdetails",
            name="product_received",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmingdetails",
            name="product_remaining",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmingdetails",
            name="product_sold",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
