# Generated by Django 4.1.6 on 2023-02-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_user_citizenship_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delivery",
            field=models.CharField(default="morning", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="payment",
            field=models.CharField(default="monthly", max_length=50),
        ),
    ]
