# Generated by Django 4.1.6 on 2023-02-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_user_delivery_user_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accessed_stored",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
