# Generated by Django 4.1.6 on 2023-02-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_user_accessed_stored"),
    ]

    operations = []
