# Generated by Django 4.1.6 on 2023-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20230227_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="accessed_stored",
            field=models.CharField(default="", max_length=50),
        ),
    ]
