# Generated by Django 4.1.6 on 2023-02-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_user_accessed_stored"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="accessed_stored",
        ),
    ]
