# Generated by Django 4.1.6 on 2023-02-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_user_accessed_stored"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="store",
            field=models.CharField(default="", max_length=50),
        ),
    ]
